version: '3'

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    command: >
       bash startapp.sh
    depends_on:
      - redis
    volumes:
      - .:/app/code
      - static:/app/code/static/
      - media:/app/code/media
      
  redis:
    image: redis:alpine
  celery:
    restart: always
    build: 
      context: .
    command: celery -A messenger worker -l INFO 
    
    depends_on:
      - redis
      - app
  nginx: 
    build: ./nginx
    volumes:
      - static:/app/code/static
      - media:/app/code/media
    depends_on:
      - app
    ports:
      - 80:80
volumes:
  static:
  media:

